package testgui;
import java.awt.Color;
import java.util.Random;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class GUI extends javax.swing.JFrame  {
    
    private ClassA a1 = (ClassA)null, a2 = (ClassA)null, a3 = (ClassA)null,a4 = (ClassA)null; 
    private ClassB b1 = (ClassB)null, b2 = (ClassB)null, b3 = (ClassB)null,b4 = (ClassB)null; 
    private MyServer ms = null;

    public GUI() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MMSIValue2 = new javax.swing.JTextField();
        BearingValue2 = new javax.swing.JTextField();
        SpeedValue2 = new javax.swing.JTextField();
        LongitudeValue2 = new javax.swing.JTextField();
        LattitudeValue2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Set2 = new javax.swing.JButton();
        UpdateButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LattitudeValue = new javax.swing.JTextField();
        LongitudeValue = new javax.swing.JTextField();
        SpeedValue = new javax.swing.JTextField();
        BearingValue = new javax.swing.JTextField();
        MMSIValue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Set1 = new javax.swing.JButton();
        UpdateButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        MMSIValue3 = new javax.swing.JTextField();
        BearingValue3 = new javax.swing.JTextField();
        SpeedValue3 = new javax.swing.JTextField();
        LongitudeValue3 = new javax.swing.JTextField();
        LattitudeValue3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        Set3 = new javax.swing.JButton();
        UpdateButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panel4 = new java.awt.Panel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        MMSIValue4 = new javax.swing.JTextField();
        BearingValue4 = new javax.swing.JTextField();
        SpeedValue4 = new javax.swing.JTextField();
        LongitudeValue4 = new javax.swing.JTextField();
        LattitudeValue4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        Set4 = new javax.swing.JButton();
        UpdateButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panel5 = new java.awt.Panel();
        Start = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel15.setBackground(new java.awt.Color(0, 204, 255));
        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("    Origin");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jLabel15.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(0, 204, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("     Base Station 2");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jLabel6.setOpaque(true);

        panel1.setBackground(new java.awt.Color(0, 204, 255));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setText("Lattitude");

        jLabel10.setText("Longitude");

        jLabel11.setText("Speed over ground");

        jLabel13.setText("Course over ground");

        jLabel12.setText("MMSI");

        MMSIValue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        MMSIValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMSIValue2ActionPerformed(evt);
            }
        });

        BearingValue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        BearingValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BearingValue2ActionPerformed(evt);
            }
        });

        SpeedValue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        SpeedValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedValue2ActionPerformed(evt);
            }
        });

        LongitudeValue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        LongitudeValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudeValue2ActionPerformed(evt);
            }
        });

        LattitudeValue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        LattitudeValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LattitudeValue2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Select Class type");

        jComboBox2.setBackground(new java.awt.Color(255, 204, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class A", "Class B" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        Set2.setBackground(new java.awt.Color(255, 204, 204));
        Set2.setText("Set");
        Set2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Set2ActionPerformed(evt);
            }
        });

        UpdateButton2.setBackground(new java.awt.Color(102, 255, 102));
        UpdateButton2.setText("Update");
        UpdateButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setText("Ice Break");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(114, 114, 114))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MMSIValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SpeedValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LongitudeValue2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LattitudeValue2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BearingValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(UpdateButton2)
                        .addGap(55, 55, 55)))
                .addGap(25, 25, 25))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LattitudeValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(LongitudeValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(SpeedValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(BearingValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(MMSIValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Set2)
                    .addComponent(UpdateButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton5))
        );

        panel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lattitude");

        jLabel2.setText("Longitude");

        jLabel3.setText("Speed over ground");

        jLabel4.setText("Course over ground");

        jLabel5.setText("MMSI");

        LattitudeValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        LattitudeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LattitudeValueActionPerformed(evt);
            }
        });

        LongitudeValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        LongitudeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudeValueActionPerformed(evt);
            }
        });

        SpeedValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        SpeedValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedValueActionPerformed(evt);
            }
        });

        BearingValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        BearingValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BearingValueActionPerformed(evt);
            }
        });

        MMSIValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel7.setText("Select Class type");

        jComboBox1.setBackground(new java.awt.Color(255, 204, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class A", "Class B" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Set1.setBackground(new java.awt.Color(255, 204, 204));
        Set1.setText("Set");
        Set1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Set1ActionPerformed(evt);
            }
        });

        UpdateButton1.setBackground(new java.awt.Color(102, 255, 102));
        UpdateButton1.setText("Update");
        UpdateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton1ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 102));
        jButton7.setText("Ice Break");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(37, 37, 37)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BearingValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpeedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LongitudeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LattitudeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MMSIValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))))
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateButton1))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MMSIValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LattitudeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LongitudeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SpeedValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BearingValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Set1)
                    .addComponent(UpdateButton1))
                .addGap(9, 9, 9)
                .addComponent(jButton7))
        );

        panel3.setBackground(new java.awt.Color(0, 204, 255));

        jLabel16.setText("Lattitude");

        jLabel17.setText("Longitude");

        jLabel18.setText("Speed over ground");

        jLabel19.setText("Course over ground");

        jLabel20.setText("MMSI");

        MMSIValue3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        MMSIValue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMSIValue3ActionPerformed(evt);
            }
        });

        BearingValue3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        BearingValue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BearingValue3ActionPerformed(evt);
            }
        });

        SpeedValue3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        SpeedValue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedValue3ActionPerformed(evt);
            }
        });

        LongitudeValue3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        LongitudeValue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudeValue3ActionPerformed(evt);
            }
        });

        LattitudeValue3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        LattitudeValue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LattitudeValue3ActionPerformed(evt);
            }
        });

        jLabel21.setText("Select Class type");

        jComboBox3.setBackground(new java.awt.Color(255, 204, 153));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class A", "Class B" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        Set3.setBackground(new java.awt.Color(255, 204, 204));
        Set3.setText("Set");
        Set3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Set3ActionPerformed(evt);
            }
        });

        UpdateButton3.setBackground(new java.awt.Color(102, 255, 102));
        UpdateButton3.setText("Update");
        UpdateButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setText("Ice Break");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LongitudeValue3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LattitudeValue3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MMSIValue3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SpeedValue3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UpdateButton3)
                                    .addComponent(BearingValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(113, 113, 113))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(MMSIValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(LattitudeValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(LongitudeValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(SpeedValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(BearingValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Set3)
                    .addComponent(UpdateButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton4))
        );

        panel4.setBackground(new java.awt.Color(0, 204, 255));

        jLabel22.setText("Lattitude");

        jLabel23.setText("Longitude");

        jLabel24.setText("Speed over ground");

        jLabel25.setText("Course over ground");

        jLabel26.setText("MMSI");

        MMSIValue4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        MMSIValue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMSIValue4ActionPerformed(evt);
            }
        });

        BearingValue4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        BearingValue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BearingValue4ActionPerformed(evt);
            }
        });

        SpeedValue4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        SpeedValue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedValue4ActionPerformed(evt);
            }
        });

        LongitudeValue4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        LongitudeValue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudeValue4ActionPerformed(evt);
            }
        });

        LattitudeValue4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        LattitudeValue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LattitudeValue4ActionPerformed(evt);
            }
        });

        jLabel27.setText("Select Class type");

        jComboBox4.setBackground(new java.awt.Color(255, 204, 153));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class A", "Class B" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        Set4.setBackground(new java.awt.Color(255, 204, 204));
        Set4.setText("Set");
        Set4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Set4ActionPerformed(evt);
            }
        });

        UpdateButton4.setBackground(new java.awt.Color(102, 255, 102));
        UpdateButton4.setText("Update");
        UpdateButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setText("Ice Break");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BearingValue4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel4Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(43, 43, 43)
                                .addComponent(SpeedValue4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LongitudeValue4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MMSIValue4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(LattitudeValue4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(113, 113, 113))))
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Set4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addComponent(MMSIValue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(LattitudeValue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(LongitudeValue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(SpeedValue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(BearingValue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Set4)
                    .addComponent(UpdateButton4))
                .addGap(18, 18, 18)
                .addComponent(jButton6))
        );

        jLabel8.setBackground(new java.awt.Color(0, 204, 255));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("     Base Station 3");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jLabel8.setOpaque(true);

        jLabel28.setBackground(new java.awt.Color(0, 204, 255));
        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 204));
        jLabel28.setText("     Base Station 1");
        jLabel28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jLabel28.setOpaque(true);

        panel5.setBackground(new java.awt.Color(0, 204, 255));

        Start.setBackground(new java.awt.Color(51, 153, 0));
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start)
                    .addComponent(jButton3))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(578, 578, 578))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel1.getAccessibleContext().setAccessibleName("");
        panel2.getAccessibleContext().setAccessibleName("");
        panel3.getAccessibleContext().setAccessibleName("");
        panel4.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void LattitudeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LattitudeValueActionPerformed
        
    }//GEN-LAST:event_LattitudeValueActionPerformed

    private void LongitudeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudeValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeValueActionPerformed

    private void SpeedValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeedValueActionPerformed

    private void BearingValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BearingValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BearingValueActionPerformed
    public static double latVal,latVal2,latVal3,latVal4;
    public static double lonVal,lonVal2,lonVal3,lonVal4;
    public static double speedVal,speedVal2,speedVal3,speedVal4;
    public static double courseVal,courseVal2,courseVal3,courseVal4;
    public long mmsiVal,mmsiVal2,mmsiVal3,mmsiVal4;
    public boolean flag;
    
   
    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        
        int mmsi1flag = 0;
        int mmsi2flag = 0;
        int mmsi3flag = 0;
        int mmsi4flag = 0;
        
        ms = new MyServer();
    	if (a1 != null) {
            a1.Timer();
            ms.setClassA1(a1);
    	}else if(b1 != null) 
        {
            b1.Timer();
            mmsi1flag = 1;
            ms.setClassB1(b1);
    	}
    	
    	if (a2 != null) {
            a2.Timer();
            ms.setClassA2(a2);
    	}else if(b2 != null) {
            b2.Timer();
            mmsi2flag = 1;
            ms.setClassB2(b2);
           
    	}
        if (a3 != null) {
            a3.Timer();
            ms.setClassA3(a3);
    	}else if(b3 != null) {
            b3.Timer();
            mmsi3flag = 1;
            ms.setClassB3(b3);          
    	}
        
        if (a4 != null) {
            a4.Timer();
            ms.setClassA4(a4);
    	}else if(b4 != null) {
            b4.Timer();
            mmsi4flag = 1;
            ms.setClassB4(b4);
           
    	}
       
        ms.Server();

      
    }//GEN-LAST:event_StartActionPerformed



    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void MMSIValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMSIValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMSIValue2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void Set2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Set2ActionPerformed
        latVal2 = Double.parseDouble(LattitudeValue2.getText());
        lonVal2 = Double.parseDouble(LongitudeValue2.getText());
        speedVal2 = Double.parseDouble(SpeedValue2.getText());
        courseVal2 = Double.parseDouble(BearingValue2.getText());       
        mmsiVal2 = Long.parseLong(MMSIValue2.getText());
        
        if (jComboBox2.getSelectedItem().equals("Class A")) 
        {
            a2 = new ClassA();
            a2.setMMSI(mmsiVal2);
            a2.setLat(latVal2);
            a2.setLon(lonVal2);
            a2.setSpeed(speedVal2);
            a2.setCourse(courseVal2);        
        }    
        else if (jComboBox2.getSelectedItem().equals("Class B")){
            b2 = new ClassB();
            b2.setMMSIB(mmsiVal2);
            b2.setLatB(latVal2);
            b2.setLonB(lonVal2);
            b2.setSpeedB(speedVal2);
            b2.setCourseB(courseVal2);  
        }
    }//GEN-LAST:event_Set2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LattitudeValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LattitudeValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LattitudeValue2ActionPerformed

    private void Set1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Set1ActionPerformed
        latVal = Double.parseDouble(LattitudeValue.getText());
        lonVal = Double.parseDouble(LongitudeValue.getText());
        speedVal = Double.parseDouble(SpeedValue.getText());
        courseVal = Double.parseDouble(BearingValue.getText());       
        mmsiVal = Long.parseLong(MMSIValue.getText());       
               
        if (jComboBox1.getSelectedItem().equals("Class A")) 
        {
            a1 = new ClassA();
            a1.setMMSI(mmsiVal);
            a1.setLat(latVal);
            a1.setLon(lonVal);
            a1.setSpeed(speedVal);
            a1.setCourse(courseVal);        
        }    
        else if (jComboBox1.getSelectedItem().equals("Class B"))
        {
            b1 = new ClassB();
            b1.setMMSIB(mmsiVal);
            b1.setLatB(latVal);
            b1.setLonB(lonVal);
            b1.setSpeedB(speedVal);
            b1.setCourseB(courseVal);   
        }
       
    }//GEN-LAST:event_Set1ActionPerformed

    private void LongitudeValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudeValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeValue2ActionPerformed

    private void SpeedValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeedValue2ActionPerformed

    private void BearingValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BearingValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BearingValue2ActionPerformed
   

    private void UpdateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton1ActionPerformed
        latVal = Double.parseDouble(LattitudeValue.getText());
        lonVal = Double.parseDouble(LongitudeValue.getText());
        speedVal = Double.parseDouble(SpeedValue.getText());
        courseVal = Double.parseDouble(BearingValue.getText()); 
        mmsiVal = Long.parseLong(MMSIValue.getText());
        //if((a1.getMMSI() == mmsiVal) || (b1.getMMSI() == mmsiVal) )
        {                              
            if (jComboBox1.getSelectedItem().equals("Class A")) 
            {
                if((a1.getMMSI() == mmsiVal))
                {
                a1.setMMSI(mmsiVal);
                a1.setLat(latVal);
                a1.setLon(lonVal);
                a1.setSpeed(speedVal);
                a1.setCourse(courseVal);        
                }  
            }
            else if (jComboBox1.getSelectedItem().equals("Class B"))
            {
                if((b1.getMMSI() == mmsiVal))
                {
                b1.setMMSIB(mmsiVal);
                b1.setLatB(latVal);
                b1.setLonB(lonVal);
                b1.setSpeedB(speedVal);
                b1.setCourseB(courseVal);   
            }
        }
    }
    }//GEN-LAST:event_UpdateButton1ActionPerformed

    private void UpdateButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton2ActionPerformed
        latVal2 = Double.parseDouble(LattitudeValue2.getText());
        lonVal2 = Double.parseDouble(LongitudeValue2.getText());
        speedVal2 = Double.parseDouble(SpeedValue2.getText());
        courseVal2 = Double.parseDouble(BearingValue2.getText());       
        mmsiVal2 = Long.parseLong(MMSIValue2.getText());
        
        
                    
        if (jComboBox2.getSelectedItem().equals("Class A")) 
            {
                if(a2.getMMSI() == mmsiVal2)
                {    
                    a2.setMMSI(mmsiVal2);
                    a2.setLat(latVal2);
                    a2.setLon(lonVal2);
                    a2.setSpeed(speedVal2);
                    a2.setCourse(courseVal2);  
                }
            }    
        if (jComboBox2.getSelectedItem().equals("Class B"))
            {
                if(b2.getMMSI() == mmsiVal2)
                {
                    
                    b2.setMMSIB(mmsiVal2);
                    b2.setLatB(latVal2);
                    b2.setLonB(lonVal2);
                    b2.setSpeedB(speedVal2);
                    b2.setCourseB(courseVal2);  
                }
            }
        
        
    }//GEN-LAST:event_UpdateButton2ActionPerformed

    private void MMSIValue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMSIValue3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMSIValue3ActionPerformed

    private void BearingValue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BearingValue3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BearingValue3ActionPerformed

    private void SpeedValue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedValue3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeedValue3ActionPerformed

    private void LongitudeValue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudeValue3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeValue3ActionPerformed

    private void LattitudeValue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LattitudeValue3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LattitudeValue3ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void Set3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Set3ActionPerformed
        latVal3 = Double.parseDouble(LattitudeValue3.getText());
        lonVal3 = Double.parseDouble(LongitudeValue3.getText());
        speedVal3 = Double.parseDouble(SpeedValue3.getText());
        courseVal3 = Double.parseDouble(BearingValue3.getText());       
        mmsiVal3 = Long.parseLong(MMSIValue3.getText());       
               
        if (jComboBox3.getSelectedItem().equals("Class A")) 
        {
            a3 = new ClassA();
            a3.setMMSI(mmsiVal3);
            a3.setLat(latVal3);
            a3.setLon(lonVal3);
            a3.setSpeed(speedVal3);
            a3.setCourse(courseVal3);        
        }    
        else if (jComboBox3.getSelectedItem().equals("Class B"))
        {
            b3 = new ClassB();
            b3.setMMSIB(mmsiVal3);
            b3.setLatB(latVal3);
            b3.setLonB(lonVal3);
            b3.setSpeedB(speedVal3);
            b3.setCourseB(courseVal3);   
        }
    }//GEN-LAST:event_Set3ActionPerformed

    private void UpdateButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton3ActionPerformed
        latVal3 = Double.parseDouble(LattitudeValue3.getText());
        lonVal3 = Double.parseDouble(LongitudeValue3.getText());
        speedVal3 = Double.parseDouble(SpeedValue3.getText());
        courseVal3 = Double.parseDouble(BearingValue3.getText()); 
        mmsiVal3 = Long.parseLong(MMSIValue3.getText());
         
                                    
        if (jComboBox3.getSelectedItem().equals("Class A")) 
            {
                if((a3.getMMSI() == mmsiVal3) )
                {
                a3.setMMSI(mmsiVal3);
                a3.setLat(latVal3);
                a3.setLon(lonVal3);
                a3.setSpeed(speedVal3);
                a3.setCourse(courseVal3);        
                }    
            }
        if (jComboBox3.getSelectedItem().equals("Class B"))
            {
                if(b3.getMMSI() == mmsiVal3)
                {
                b3.setMMSIB(mmsiVal3);
                b3.setLatB(latVal3);
                b3.setLonB(lonVal3);
                b3.setSpeedB(speedVal3);
                b3.setCourseB(courseVal3);   
                }
        }
    }//GEN-LAST:event_UpdateButton3ActionPerformed

    private void MMSIValue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMSIValue4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMSIValue4ActionPerformed

    private void BearingValue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BearingValue4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BearingValue4ActionPerformed

    private void SpeedValue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedValue4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeedValue4ActionPerformed

    private void LongitudeValue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudeValue4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeValue4ActionPerformed

    private void LattitudeValue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LattitudeValue4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LattitudeValue4ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void Set4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Set4ActionPerformed
       latVal4 = Double.parseDouble(LattitudeValue4.getText());
        lonVal4 = Double.parseDouble(LongitudeValue4.getText());
        speedVal4 = Double.parseDouble(SpeedValue4.getText());
        courseVal4 = Double.parseDouble(BearingValue4.getText());       
        mmsiVal4 = Long.parseLong(MMSIValue4.getText());       
               
        if (jComboBox4.getSelectedItem().equals("Class A")) 
        {
            a4 = new ClassA();
            a4.setMMSI(mmsiVal4);
            a4.setLat(latVal4);
            a4.setLon(lonVal4);
            a4.setSpeed(speedVal4);
            a4.setCourse(courseVal4);        
        }    
        else if (jComboBox4.getSelectedItem().equals("Class B"))
        {
            b4 = new ClassB();
            b4.setMMSIB(mmsiVal4);
            b4.setLatB(latVal4);
            b4.setLonB(lonVal4);
            b4.setSpeedB(speedVal4);
            b4.setCourseB(courseVal4);   
        }
    }//GEN-LAST:event_Set4ActionPerformed

    private void UpdateButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton4ActionPerformed
        latVal4 = Double.parseDouble(LattitudeValue4.getText());
        lonVal4 = Double.parseDouble(LongitudeValue4.getText());
        speedVal4 = Double.parseDouble(SpeedValue4.getText());
        courseVal4 = Double.parseDouble(BearingValue4.getText()); 
        mmsiVal4 = Long.parseLong(MMSIValue4.getText());
                                     
            if (jComboBox4.getSelectedItem().equals("Class A")) 
            {
                 if(a4.getMMSI() == mmsiVal4)
                 {
                    a4.setMMSI(mmsiVal4);
                    a4.setLat(latVal4);
                    a4.setLon(lonVal4);
                    a4.setSpeed(speedVal4);
                    a4.setCourse(courseVal4); 
                 }
            }    
            else if (jComboBox4.getSelectedItem().equals("Class B"))
            {
                if(b4.getMMSI() == mmsiVal4)
                {
                    b4.setMMSIB(mmsiVal4);
                    b4.setLatB(latVal4);
                    b4.setLonB(lonVal4);
                    b4.setSpeedB(speedVal4);
                    b4.setCourseB(courseVal4); 
                }
            }        
    }//GEN-LAST:event_UpdateButton4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Random rand = new Random(); 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        latVal = Double.parseDouble(LattitudeValue.getText());
        lonVal = Double.parseDouble(LongitudeValue.getText());
        speedVal = Double.parseDouble(SpeedValue.getText());
        courseVal = Double.parseDouble(BearingValue.getText()); 
        mmsiVal = Long.parseLong(MMSIValue.getText());
       if ((latVal > 0) || (latVal < 0 ))
       {
           latVal *= -1;          
       }
       if ((lonVal > 0) || (lonVal < 0 ))
       {
           lonVal *= -1;          
       }   
        {                              
            if (jComboBox1.getSelectedItem().equals("Class A")) 
            {
                if((a1.getMMSI() == mmsiVal))
                {
                a1.setMMSI(mmsiVal);
                a1.setLat(latVal);
                a1.setLon(lonVal);
                a1.setSpeed(speedVal);
                a1.setCourse(courseVal);        
                }  
            }
            else if (jComboBox1.getSelectedItem().equals("Class B"))
            {
                if((b1.getMMSI() == mmsiVal))
                {
                b1.setMMSIB(mmsiVal);
                b1.setLatB(latVal);
                b1.setLonB(lonVal);
                b1.setSpeedB(speedVal);
                b1.setCourseB(courseVal);   
            }
        }
    }
    }//GEN-LAST:event_jButton7ActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
       
       
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BearingValue;
    private javax.swing.JTextField BearingValue2;
    private javax.swing.JTextField BearingValue3;
    private javax.swing.JTextField BearingValue4;
    private javax.swing.JTextField LattitudeValue;
    private javax.swing.JTextField LattitudeValue2;
    private javax.swing.JTextField LattitudeValue3;
    private javax.swing.JTextField LattitudeValue4;
    private javax.swing.JTextField LongitudeValue;
    private javax.swing.JTextField LongitudeValue2;
    private javax.swing.JTextField LongitudeValue3;
    private javax.swing.JTextField LongitudeValue4;
    private javax.swing.JTextField MMSIValue;
    private javax.swing.JTextField MMSIValue2;
    private javax.swing.JTextField MMSIValue3;
    private javax.swing.JTextField MMSIValue4;
    private javax.swing.JButton Set1;
    private javax.swing.JButton Set2;
    private javax.swing.JButton Set3;
    private javax.swing.JButton Set4;
    private javax.swing.JTextField SpeedValue;
    private javax.swing.JTextField SpeedValue2;
    private javax.swing.JTextField SpeedValue3;
    private javax.swing.JTextField SpeedValue4;
    public javax.swing.JButton Start;
    private javax.swing.JButton UpdateButton1;
    private javax.swing.JButton UpdateButton2;
    private javax.swing.JButton UpdateButton3;
    private javax.swing.JButton UpdateButton4;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    // End of variables declaration//GEN-END:variables
}
